# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
 pipelines:
     - pipeline: 'buildPipeline'
       project: 'DSC'
       source: 'BuildPipeline'
       branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'VM_IIS_1.win2022-iis-vm1'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'BuildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'AzureTestProjects'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: '${{ variables.IISWebsiteName }}'
                    WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
                    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy IIS website'                
                  inputs:
                    WebSiteName: '${{ variables.IISWebsiteName }}'
                    Package: '$(Pipeline.Workspace)\BuildPipeline\AzureTestProjects\RoundTheCode.AzureTestProject'
                    TakeAppOfflineFlag: true
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS website'                     
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'