# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  websiteName: 'AzureTestProject'
  websitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\$(websiteName)'
  appPoolName: 'AzureTestProject'


resources:
 pipelines:
     - pipeline: 'buildPipeline'
       project: 'DSC'
       source: 'BuildPipeline'
       branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'VM_IIS_1.win2022-iis-vm1'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'BuildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'AzureTestProjects'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                   IISDeploymentType: 'IISWebsite'
                   ActionIISWebsite: 'CreateOrUpdateWebsite'
                   WebsiteName: '$(websiteName)'
                   WebsitePhysicalPath: '$(websitePhysicalPath)'
                   CreateOrUpdateAppPoolForWebsite: true
                   AppPoolNameForWebsite: '$(appPoolName)'
                   DotNetVersionForWebsite: 'No Managed Code'
                   PipeLineModeForWebsite: 'Integrated'
                   AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                   AddBinding: true
                   Bindings: |
                       {
                           bindings:[
                               {
                                   "protocol":"http",
                                   "ipAddress":"",
                                   "hostname":"",
                                   "port":"80",
                                   "sslThumbprint":"",
                                   "sniFlag":false
                                 }
                             ]
                         }
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: '$(websiteName)'
                    Package: '$(Pipeline.Workspace)\BuildPipeline\AzureTestProjects\RoundTheCode.AzureTestProject'